# api/config/routes.yaml
auth:
    path: login
    methods: ['POST']
data_game:
    path: api/data-game
    controller: App\Controller\DataGameLightData::__invoke
data_user_for_main_page:
    path: api/data-user-for-main-page
    controller: App\Controller\DataUserLightData::__invoke
games_by_player:
    path: api/games-by-player/{id}
    controller: App\Controller\GamesByUser::__invoke
search_player:
    path: api/search-user/{string}
    controller: App\Controller\SearchUser::__invoke
update_elo:
    path: api/update-elo/{id}
    controller: App\Controller\UpdateElo::__invoke
find_elo_by_user:
    path: api/find-elo-by-user/{id}/{idGame}
    controller: App\Controller\FindElo::__invoke
find_coach:
    path: api/find-coach
    controller: App\Controller\DataUserLightDataRoleCoach::__invoke
search_coach:
    path: api/search-coach/{string}
    controller: App\Controller\SearchCoach::__invoke
find_message_by_messenger:
    path: api/find-message-by-messenger/{idUserSend}/{idUserReceive}
    controller: App\Controller\FindMessageByMessenger::__invoke
find_message_by_user:
    path: api/find-message-by-user/{idUser}
    controller: App\Controller\FindMessageByUser::__invoke
